form:
    resource: "@FormBundle/Resources/config/routing.yml"
    prefix:   /

symfony:
    resource: "@SymfonyBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
