symfony_homepage:
    path:     /test_homepage
    defaults: { _controller: SymfonyBundle:Default:index }

all_entite:
    path:     /entiteAll
    defaults: { _controller: SymfonyBundle:Array:crrreate }    


test_task:
    path: /test_task
    defaults: { _controller: SymfonyBundle:Task:new}