AppBundle\Entity\Entite:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\EntiteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
        price:
            type: decimal
            precision: '2'
            scale: '2'
        published:
            type: boolean    
    lifecycleCallbacks: {  }
